# Generated by Django 5.2.5 on 2025-09-04 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pf_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('teaching', 'Teaching Staff'), ('non_teaching', 'Non-Teaching Staff'), ('supervisor', 'Supervisor')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonTeachingStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('school_or_department', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('terms_of_service', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract')], max_length=20)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'non_teaching'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonTeachingAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_under_review', models.CharField(max_length=100)),
                ('length_of_service', models.CharField(max_length=50)),
                ('years_in_equivalent_position', models.CharField(max_length=50)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('appraisal_date', models.DateField()),
                ('acting_or_special_duty', models.CharField(help_text="E.g. 'Acting Librarian – 2 months' or 'None'", max_length=255, verbose_name='Acting/Special Duty (state duration)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='users.nonteachingstaffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('terms_of_service', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract')], max_length=20)),
                ('school_or_department', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingStaffAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField()),
                ('acting_appointment', models.TextField(blank=True, null=True)),
                ('years_experience_kyu', models.PositiveIntegerField(default=0)),
                ('years_experience_elsewhere', models.PositiveIntegerField(default=0)),
                ('supervisor_name', models.CharField(max_length=255)),
                ('supervisor_designation', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='users.teachingstaffprofile')),
            ],
        ),
    ]
