# Generated by Django 5.2.5 on 2025-09-08 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingstaffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='teachingstaffprofile',
            name='personal_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachingstaffprofile',
            name='school_or_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teachingstaffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachingstaffprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
