# Generated by Django 5.2.5 on 2025-11-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supervisorevaluation",
            name="self_assessment",
        ),
        migrations.RemoveField(
            model_name="supervisorevaluation",
            name="supervisor",
        ),
        migrations.DeleteModel(
            name="SelfAssessment",
        ),
        migrations.DeleteModel(
            name="SupervisorEvaluation",
        ),
    ]
