# Generated by Django 5.2.5 on 2025-09-11 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teachingstaffprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonteachingstaffprofile',
            old_name='job_title',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='nonteachingstaffprofile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='nonteachingstaffprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nonteachingstaffprofile',
            name='school_or_department',
        ),
        migrations.RemoveField(
            model_name='nonteachingstaffprofile',
            name='terms_of_service',
        ),
        migrations.RemoveField(
            model_name='teachingstaffprofile',
            name='personal_number',
        ),
        migrations.RemoveField(
            model_name='teachingstaffprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='teachingstaffprofile',
            name='school_or_department',
        ),
        migrations.RemoveField(
            model_name='teachingstaffprofile',
            name='terms_of_service',
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_of_service',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='nonteachingstaffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachingstaffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nonteachingstaffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachingstaffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
