# Generated by Django 5.2.5 on 2025-11-12 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "spe",
            "0004_speperiod_current_phase_speperiod_evaluation_end_and_more",
        ),
        ("users", "0002_remove_supervisorevaluation_self_assessment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetarget",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancetarget",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_targets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spe.speperiod"
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_targets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="performancetarget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft - Being Filled by Staff"),
                    ("submitted", "Submitted for Approval"),
                    ("approved", "Approved - Ready for Evaluation"),
                    ("rejected", "Rejected - Needs Revision"),
                    ("evaluated", "Evaluated - Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
