# Generated by Django 5.2.5 on 2025-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_performancetarget_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_hr",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("teaching", "Teaching Staff"),
                    ("non_teaching", "Non-Teaching Staff"),
                    ("supervisor", "Supervisor"),
                    ("hr", "HR Staff"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="staff_type",
            field=models.CharField(
                choices=[
                    ("teaching", "Teaching"),
                    ("non_teaching", "Non-Teaching"),
                    ("supervisor", "Supervisor"),
                    ("hr", "HR"),
                ],
                max_length=20,
            ),
        ),
    ]
