# Generated by Django 5.2.5 on 2025-11-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_departmentappraisal_departmentappraisalitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_vc",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("teaching", "Teaching Staff"),
                    ("non_teaching", "Non-Teaching Staff"),
                    ("supervisor", "Supervisor"),
                    ("hr", "HR Staff"),
                    ("vc", "Vice Chancellor"),
                ],
                max_length=20,
            ),
        ),
    ]
