# Generated by Django 6.0 on 2026-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_is_vc_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, help_text="Department description"),
        ),
        migrations.AlterField(
            model_name="department",
            name="staff_type",
            field=models.CharField(
                choices=[
                    ("teaching", "Teaching"),
                    ("non_teaching", "Non-Teaching"),
                    ("supervisor", "Supervisor"),
                    ("hr", "HR"),
                    ("mixed", "Mixed"),
                    ("any", "Any"),
                ],
                default="any",
                max_length=20,
            ),
        ),
    ]
