# Generated by Django 5.2.5 on 2025-11-14 12:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spe", "0005_remove_speperiod_forms_approved_by_admin_and_more"),
        ("users", "0004_customuser_is_hr_alter_customuser_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("department", "Department Performance Report"),
                            ("supervisor", "Supervisor Effectiveness Report"),
                            (
                                "institutional",
                                "Institutional Analytics Report",
                            ),
                            ("comparative", "Comparative Analysis Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        help_text="Generated report file",
                        upload_to="hr_reports/%Y/%m/",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Report generation parameters",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for institutional-wide reports",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.department",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        limit_choices_to={"is_hr": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spe.speperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institutional Report",
                "verbose_name_plural": "Institutional Reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="SupervisorAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("leadership", "Leadership & Team Management"),
                            ("strategic", "Strategic & Planning"),
                            ("operational", "Operational Excellence"),
                            ("development", "Staff Development & Mentoring"),
                            ("communication", "Communication & Collaboration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of this attribute"
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=0,
                        help_text="Weight in percentage (e.g., 15 for 15%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_hr": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supervisor_attributes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor Attribute",
                "verbose_name_plural": "Supervisor Attributes",
                "ordering": ["category", "weight", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupervisorIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Specific behavior or competency to evaluate"
                    ),
                ),
                (
                    "example",
                    models.TextField(
                        blank=True,
                        help_text="Example of what this looks like in practice",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="hr.supervisorattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor Indicator",
                "verbose_name_plural": "Supervisor Indicators",
                "ordering": ["attribute", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SupervisorAppraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Overall weighted score percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("finalized", "Finalized"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supervisor_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Supervisor's comments on appraisal",
                    ),
                ),
                (
                    "feedback_submitted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_hr": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_supervisor_appraisals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_appraisals",
                        to="spe.speperiod",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        limit_choices_to={"role": "supervisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_appraisals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor Appraisal",
                "verbose_name_plural": "Supervisor Appraisals",
                "ordering": ["-period__start_date", "supervisor"],
                "unique_together": {("supervisor", "period")},
            },
        ),
        migrations.CreateModel(
            name="SupervisorEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor Leadership"),
                            (2, "2 - Developing"),
                            (3, "3 - Competent"),
                            (4, "4 - Strong Leader"),
                            (5, "5 - Exceptional Leader"),
                        ]
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="HR's comments on this rating"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.supervisorattribute",
                    ),
                ),
                (
                    "hr_user",
                    models.ForeignKey(
                        limit_choices_to={"is_hr": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_evaluations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_evaluations",
                        to="spe.speperiod",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        limit_choices_to={"role": "supervisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_evaluations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.supervisorindicator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor HR Evaluation",
                "verbose_name_plural": "Supervisor HR Evaluations",
                "ordering": [
                    "supervisor",
                    "attribute__category",
                    "attribute__weight",
                ],
                "unique_together": {
                    ("supervisor", "period", "attribute", "hr_user")
                },
            },
        ),
    ]
