# Generated by Django 5.2.5 on 2025-11-17 13:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_institutionalreport_generated_by_and_more"),
        ("spe", "0006_supervisorrating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supervisorappraisal",
            options={
                "verbose_name": "Supervisor Appraisal",
                "verbose_name_plural": "Supervisor Appraisals",
            },
        ),
        migrations.AlterUniqueTogether(
            name="supervisorappraisal",
            unique_together={("supervisor", "period", "evaluated_by")},
        ),
        migrations.AddField(
            model_name="supervisorappraisal",
            name="average_score",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supervisorappraisal",
            name="percentage_score",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supervisorappraisal",
            name="total_score",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supervisorappraisal",
            name="evaluated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supervisorappraisal",
            name="evaluated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_appraisals_given",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supervisorappraisal",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_period_appraisals",
                to="spe.speperiod",
            ),
        ),
        migrations.AlterField(
            model_name="supervisorappraisal",
            name="status",
            field=models.CharField(default="draft", max_length=20),
        ),
        migrations.AlterField(
            model_name="supervisorappraisal",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_appraisals_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SupervisorAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spe.speattribute",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spe.speindicator",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spe.speperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor Assessment",
                "verbose_name_plural": "Supervisor Assessments",
                "unique_together": {("period", "attribute", "indicator")},
            },
        ),
        migrations.RemoveField(
            model_name="supervisorappraisal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="supervisorappraisal",
            name="feedback_submitted_at",
        ),
        migrations.RemoveField(
            model_name="supervisorappraisal",
            name="overall_score",
        ),
        migrations.RemoveField(
            model_name="supervisorappraisal",
            name="supervisor_feedback",
        ),
        migrations.RemoveField(
            model_name="supervisorappraisal",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="SupervisorEvaluationByStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("staff_remarks", models.TextField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spe.speperiod",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_given_supervisor_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_received_supervisor_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.supervisorassessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Supervisor Evaluation",
                "verbose_name_plural": "Staff Supervisor Evaluations",
                "unique_together": {
                    ("supervisor_assessment", "staff", "supervisor", "period")
                },
            },
        ),
        migrations.CreateModel(
            name="SupervisorOverallEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_submitted", models.BooleanField(default=False)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spe.speattribute",
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spe.speindicator",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spe.speperiod",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overall_supervisor_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor Overall Evaluation",
                "verbose_name_plural": "Supervisor Overall Evaluations",
                "unique_together": {
                    (
                        "supervisor",
                        "period",
                        "attribute",
                        "indicator",
                        "evaluated_by",
                    )
                },
            },
        ),
    ]
