# Generated by Django 5.2.5 on 2025-11-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_supervisorappraisal_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supervisorappraisal",
            name="percentage_score",
        ),
        migrations.AddField(
            model_name="supervisorappraisal",
            name="overall_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="supervisorappraisal",
            name="average_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="supervisorappraisal",
            name="total_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="supervisorassessment",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.supervisorattribute",
            ),
        ),
        migrations.AlterField(
            model_name="supervisorassessment",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.supervisorindicator",
            ),
        ),
        migrations.AlterField(
            model_name="supervisoroverallevaluation",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.supervisorattribute",
            ),
        ),
        migrations.AlterField(
            model_name="supervisoroverallevaluation",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.supervisorindicator",
            ),
        ),
    ]
