# Generated by Django 5.2.5 on 2025-11-18 10:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_supervisorevaluation_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisorperformancetarget",
            name="achievement_percentage",
            field=models.FloatField(
                blank=True,
                help_text="Percentage of target achieved (0-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Achievement Percentage",
            ),
        ),
        migrations.AddField(
            model_name="supervisorperformancetarget",
            name="performance_comments",
            field=models.TextField(
                blank=True, null=True, verbose_name="Performance Comments"
            ),
        ),
        migrations.AddField(
            model_name="supervisorperformancetarget",
            name="performance_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 - Poor"),
                    (2, "2 - Fair"),
                    (3, "3 - Good"),
                    (4, "4 - Very Good"),
                    (5, "5 - Excellent"),
                ],
                null=True,
                verbose_name="Performance Rating",
            ),
        ),
        migrations.AddField(
            model_name="supervisorperformancetarget",
            name="rated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supervisorperformancetarget",
            name="rated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rated_targets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rated By",
            ),
        ),
    ]
