# Generated by Django 5.2.5 on 2025-11-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hr",
            "0006_supervisorperformancetarget_achievement_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisorappraisal",
            name="criteria_evaluated",
            field=models.IntegerField(
                default=0, verbose_name="Criteria Evaluated Count"
            ),
        ),
        migrations.AddField(
            model_name="supervisorappraisal",
            name="criteria_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Criteria Score"
            ),
        ),
        migrations.AddField(
            model_name="supervisorappraisal",
            name="target_achievement_rate",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Target Achievement Rate"
            ),
        ),
        migrations.AddField(
            model_name="supervisorappraisal",
            name="target_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Target Score"
            ),
        ),
        migrations.AddField(
            model_name="supervisorappraisal",
            name="targets_evaluated",
            field=models.IntegerField(
                default=0, verbose_name="Targets Evaluated Count"
            ),
        ),
        migrations.AlterField(
            model_name="supervisorevaluation",
            name="comments",
            field=models.TextField(
                blank=True, help_text="HR's comments on this rating", null=True
            ),
        ),
    ]
