# Generated by Django 5.2.5 on 2025-11-18 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_supervisorappraisal_criteria_evaluated_and_more"),
        ("spe", "0006_supervisorrating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supervisorevaluation",
            unique_together={
                ("supervisor", "period", "attribute", "indicator", "hr_user")
            },
        ),
    ]
