# Generated by Django 5.2.5 on 2025-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_alter_supervisorevaluation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="supervisorperformancetarget",
            name="success_measures",
            field=models.TextField(
                blank=True,
                help_text="Specific measures to evaluate success. Enter one per line.",
                null=True,
                verbose_name="Success Measures / KPIs",
            ),
        ),
    ]
