# Generated by Django 5.2.5 on 2025-09-04 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPEAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SPEPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPEIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='spe.speattribute')),
            ],
        ),
        migrations.AddField(
            model_name='speattribute',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='spe.speperiod'),
        ),
        migrations.CreateModel(
            name='NonTeachingStaffEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trs', models.FloatField(default=0)),
                ('mrs', models.FloatField(default=0)),
                ('percent_score', models.FloatField(default=0)),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'non_teaching'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spe.speattribute')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spe.speindicator')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spe.speperiod')),
            ],
        ),
    ]
