# Generated by Django 5.2.5 on 2025-09-08 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingStaffEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trs', models.FloatField(default=0)),
                ('mrs', models.FloatField(default=0)),
                ('percent_score', models.FloatField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spe.speattribute')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spe.speindicator')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spe.speperiod')),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'teaching'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
