# Generated by Django 5.2.5 on 2025-11-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("spe", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationcomment",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spe_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluationcomment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="nonteachingstaffevaluation",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_reviewed_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nonteachingstaffevaluation",
            name="staff",
            field=models.ForeignKey(
                limit_choices_to={"role": "non_teaching"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_teaching_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="selfassessment",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spe_self_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="speattribute",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor who created this attribute",
                limit_choices_to={"role": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="speattribute",
            name="department",
            field=models.ForeignKey(
                help_text="Department this attribute belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="selfassessment",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spe_self_assessments",
                to="spe.speattribute",
            ),
        ),
        migrations.AddField(
            model_name="nonteachingstaffevaluation",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spe.speattribute",
            ),
        ),
        migrations.AddField(
            model_name="speindicator",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indicators",
                to="spe.speattribute",
            ),
        ),
        migrations.AddField(
            model_name="selfassessment",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spe_self_assessments",
                to="spe.speindicator",
            ),
        ),
        migrations.AddField(
            model_name="nonteachingstaffevaluation",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spe.speindicator",
            ),
        ),
        migrations.AddField(
            model_name="speattribute",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="spe.speperiod",
            ),
        ),
        migrations.AddField(
            model_name="selfassessment",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spe.speperiod"
            ),
        ),
        migrations.AddField(
            model_name="nonteachingstaffevaluation",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spe.speperiod"
            ),
        ),
        migrations.AddField(
            model_name="departmentsummary",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spe.speperiod"
            ),
        ),
        migrations.AddField(
            model_name="staffresult",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spe.speperiod"
            ),
        ),
        migrations.AddField(
            model_name="staffresult",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supervisorevaluation",
            name="self_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spe_supervisor_evaluation",
                to="spe.selfassessment",
            ),
        ),
        migrations.AddField(
            model_name="supervisorevaluation",
            name="supervisor",
            field=models.ForeignKey(
                limit_choices_to={"role": "supervisor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spe_supervisor_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teachingstaffevaluation",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spe.speattribute",
            ),
        ),
        migrations.AddField(
            model_name="teachingstaffevaluation",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spe.speindicator",
            ),
        ),
        migrations.AddField(
            model_name="teachingstaffevaluation",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spe.speperiod"
            ),
        ),
        migrations.AddField(
            model_name="teachingstaffevaluation",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "supervisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_reviewed_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teachingstaffevaluation",
            name="staff",
            field=models.ForeignKey(
                limit_choices_to={"role": "teaching"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="speattribute",
            unique_together={("name", "period", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="selfassessment",
            unique_together={("staff", "period", "indicator")},
        ),
        migrations.AlterUniqueTogether(
            name="nonteachingstaffevaluation",
            unique_together={("staff", "period", "indicator")},
        ),
        migrations.AlterUniqueTogether(
            name="departmentsummary",
            unique_together={("period", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="staffresult",
            unique_together={("staff", "period")},
        ),
        migrations.AlterUniqueTogether(
            name="supervisorevaluation",
            unique_together={("supervisor", "self_assessment")},
        ),
        migrations.AlterUniqueTogether(
            name="teachingstaffevaluation",
            unique_together={("staff", "period", "indicator")},
        ),
    ]
