# Generated by Django 5.2.5 on 2025-11-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spe", "0002_initial"),
        ("users", "0002_remove_supervisorevaluation_self_assessment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentsummary",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
            ),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
