# Generated by Django 5.2.5 on 2025-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spe', '0002_teachingstaffevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaffevaluation',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachingstaffevaluation',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
