# Generated by Django 5.2.5 on 2025-11-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "spe",
            "0004_speperiod_current_phase_speperiod_evaluation_end_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speperiod",
            name="forms_approved_by_admin",
        ),
        migrations.RemoveField(
            model_name="speperiod",
            name="forms_visible_to_staff",
        ),
        migrations.AddField(
            model_name="speperiod",
            name="forms_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft - Supervisors Working"),
                    ("ready", "Ready for Staff"),
                    ("closed", "Closed - Evaluation Complete"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
