# Generated by Django 5.2.5 on 2025-11-19 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spe", "0006_supervisorrating"),
        ("users", "0005_departmentappraisal_departmentappraisalitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="speattribute",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this attribute",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="speattribute",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department this attribute belongs to (leave empty for global forms)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
            ),
        ),
    ]
